// DONT EDIT THIS CODE!
// AUTOGENERATED BY DASHA STUDIO
/* eslint-disable no-undef */

import axios from "axios";
import graph from "./graph.json";
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

export default class TelegramAvatar {
  currentNode = "";
  currentJobId = "";

  telegramKey = null;
  telegram = "";

  constructor(key, enpoint) {
    this.telegram = enpoint;
    this.telegramKey = key;
  }

  async connect(job) {
    if (this.currentJobId) return;
    this.currentJobId = job;

    await axios.post(`${this.telegram}/connect`, {
      id: this.telegramKey,
      nodes: graph.nodesLinks,
      jobId: job,
    });
  }

  disconnect = async () => {
    await axios.post(`${this.telegram}/disconnect`, { id: this.telegramKey });
  };

  setCurrentNode(node) {
    this.currentNode = node;
  }

  dashaMessage = async (message) => {
    await axios.post(`${this.telegram}/dasha`, { id: this.telegramKey, message });
  };

  userMessage = async (data) => {
    await delay(500);

    const node = this.currentNode?.split(":").pop();
    const result = await axios.post(`${this.telegram}/message`, {
      id: this.telegramKey,
      suggestions: node ? graph.nodesLinks[node] ?? [] : [],
      currentNode: this.currentNode,
      message: data.message,
      ctx: data.ctx,
    });

    return result.data;
  };
}
